### ISSUE TITLE
Warning plot_feature_stability_ecs_incremental:  invalid factor level, NA generated

### ISSUE THREAD

**Issue by aciobanusebi** [Core-Bioinformatics/ClustAssess#1]
I think it is safe to add `stringAsFactors=F` [here](https://github.com/Core-Bioinformatics/ClustAssess/blob/8e026521fe5bc200d5fb983d47189f8a0768d9f8/R/stability-based-parameter-assessment.R#L670).

since I used it with another dataset and got 

```
Warning message:
In `[<-.factor`(`*tmp*`, ri, value = "462-581") :
  invalid factor level, NA generated
```
The effect of using `stringAsFactors=F` is that instead of obtaining:
![image](https://user-images.githubusercontent.com/17072091/164245231-cc4c4802-5b9b-4789-9cb9-be28292d3061.png)

I get the top text labels:
![image](https://user-images.githubusercontent.com/17072091/164245302-01735189-09ec-4e1c-9dce-5d9b4d061c05.png)

I am not sure why I got this warning since you did not get it, but I think it is safe to add `stringAsFactors=F`.

Thanks for your work!

**Comment by AndiMunteanu** [comment]
Thank you for submitting the issue.

The ClustAssess package was developed on version 4.1.0 of R and relied on the synonym version of the base packages. As presented in the `data.frame` [documentation](https://stat.ethz.ch/R-manual/R-devel/library/base/html/data.frame.html), `stringsAsFactors` was assigned FALSE as from version 4.0.0 onwards. 
We assume that the error mentioned in the issue occurred due to an older version of the `base` package. To enhance the compatibility with earlier versions of R, we have now explicitly set the `stringsAsFactors` parameter as FALSE. This corresponds to the commit 6278cae.

Thank you again for spotting this compatibility issue!
